repack_cleanup support

diff --git a/tazpkg b/tazpkg
--- a/tazpkg
+++ b/tazpkg
@@ -1027,12 +1027,6 @@ list of packages to install. Example : tazpkg install-list packages.list\n"
 			echo -e "$MISSING"
 			exit 1
 		fi
-		if [ -f $INSTALLED/$PACKAGE/md5sum ]; then
-			if ! md5sum -s -c $INSTALLED/$PACKAGE/md5sum; then
-				echo -n "Can't repack, md5sum error."
-				exit 1
-			fi
-		fi
 		mkdir -p $TMP_DIR && cd $TMP_DIR
 		FILES="fs.cpio.gz\n"
 		for i in $(ls $INSTALLED/$PACKAGE) ; do
@@ -1043,6 +1037,19 @@ list of packages to install. Example : tazpkg install-list packages.list\n"
 		sed 's/^/rootfs/' < files.list | cpio -o -H newc 2>/dev/null |\
 		      ( cd tmp ; cpio -id 2>/dev/null )
 		mv tmp/rootfs fs
+		if grep -q repack_cleanup $INSTALLED/$PACKAGE/receipt; then
+			. $INSTALLED/$PACKAGE/receipt
+			repack_cleanup fs
+		fi
+		if [ -f $INSTALLED/$PACKAGE/md5sum ]; then
+			sed 's,  ,  fs,' < $INSTALLED/$PACKAGE/md5sum | \
+			if ! md5sum -s -c; then
+				echo -n "Can't repack, md5sum error."
+				cd $TOP_DIR
+				\rm -R $TMP_DIR
+				exit 1
+			fi
+		fi
 		find fs | cpio -o -H newc 2> /dev/null | gzip -9 > fs.cpio.gz
 		echo -e "$FILES" | cpio -o -H newc 2> /dev/null > \
 			$TOP_DIR/$PACKAGE-$VERSION.tazpkg
