tazpkg/repack: fix md5sum check

diff --git a/tazpkg b/tazpkg
--- a/tazpkg
+++ b/tazpkg
@@ -1458,12 +1458,12 @@ EOT
 		fi
 		if [ -f $INSTALLED/$PACKAGE/md5sum ]; then
 			sed 's,  ,  fs,' < $INSTALLED/$PACKAGE/md5sum | \
-			if ! md5sum -s -c; then
-				echo -n "Can't repack, md5sum error."
+			md5sum -s -c || {
+				echo "Can't repack, md5sum error."
 				cd $TOP_DIR
-				\rm -R $TMP_DIR
+				rm -rf $TMP_DIR
 				exit 1
-			fi
+			}
 		fi
 		find fs | cpio -o -H newc 2> /dev/null | gzip -9 > fs.cpio.gz
 		echo -e "$FILES" | cpio -o -H newc 2> /dev/null > \
